WidgetsExample:


<WidgetsExample>: 
    cols : 3
    Button:
        text: "Click Here" 
        on_press: root.on_button_click()
    Label:
        text:root.my_text

<BoxLayoutExample> :
    orientation: "vertical"
    Button:
        text: "A"
        size: "40dp", "40dp"
        size_hint: None, None
        pos_hint: {"center_x": .5}
    Button:
        text: "B"
    Label:
        text: "C"